

#服务端口
server:
  port: 8081
#
spring:
  datasource:
      url: jdbc:mysql://localhost:3306/mymall?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
      username: root
      password: clay

#mybatis
mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml


